In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [4]:
arr = np.array([5, 10, 15, 20, 25])
print(arr)

[ 5 10 15 20 25]


In [5]:
zeros = np.zeros((3,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
identity = np.eye(4)  # 3x3 Identity matrix
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
arr = np.arange(10, 51, 5)
print(arr)

[10 15 20 25 30 35 40 45 50]


In [10]:
arr = np.array([10, 20, 30, 40])
arr2 = arr.astype(float)
print(arr2)

[10. 20. 30. 40.]


In [11]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


In [12]:
print (arr.size)

6


In [13]:
print(arr.ndim)

2


In [14]:
arr=np.array([5,10,15,20,25,30])
print(arr[0],arr[-1],arr[3])

5 30 20


In [16]:
print(arr[1:4])

[10 15 20]


In [17]:
print(arr[::-1])

[30 25 20 15 10  5]


In [21]:
print(arr[1::2])

[10 20 30]


In [22]:
marks=np.array([45,78,90,32,88,67])
print(marks[marks > 70])

[78 90 88]


In [23]:
arr = np.arange(1, 13)
arr2 = arr.reshape(3, 4)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [26]:
arr = arr2.flatten()
print(arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [27]:
result = arr * 5
print(result)

[ 5 10 15 20 25 30 35 40 45 50 55 60]


In [28]:
print(np.sum(arr),np.mean(arr),np.max(arr),np.min(arr),np.std(arr))

78 6.5 12 1 3.452052529534663


In [30]:
arr1 = np.array([[1, 2],[3, 4]])
arr2 = np.array([[5,6],[7, 8]])
print(arr1+arr2)
print(arr1*arr2)
print(arr1@arr2)

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
