In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

ones = np.ones((2, 4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[1,1])

5


In [7]:
a=[10,50,20,30,60,40]
print(np.sort(a))

[10 20 30 40 50 60]
