In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [12]:
a = int(input("Enter number 1"))
b = int(input("Enter number 2"))
c = int(input("Enter number 3"))
d = int(input("Enter number 4"))
e = int(input("Enter number 5"))
arr = np.array([a, b, c, d, e])
print(arr)

[10 20 30 40 50]


In [8]:
a = int(input("Enter sales 1"))
b = int(input("Enter sales 2"))
c = int(input("Enter sales 3"))
d = int(input("Enter sales 4"))
e = int(input("Enter sales 5"))
sales=np.array([a,b,c,d,e])
print("Total sales",np.sum(sales))
print("Average sales",np.mean(sales))
print("Highest sales",np.max(sales))
print("lowest sales",np.min(sales))

Total sales 7600
Average sales 1520.0
Highest sales 2000
lowest sales 1100


In [30]:
arr=np.arange(1,13)
arr2=arr.reshape(3,4)
print("Original array",arr)
print("3 x 4 Matrix",arr2)
print("Rows",np.shape(arr2)[0])
print("Columns",np.shape(arr2)[1])

Original array [ 1  2  3  4  5  6  7  8  9 10 11 12]
3 x 4 Matrix [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Rows 3
Columns 4


In [25]:
a = int(input("Enter salary 1"))
b = int(input("Enter salary 2"))
c = int(input("Enter salary 3"))
d = int(input("Enter salary 4"))
e = int(input("Enter salary 5"))
f = int(input("Enter salary 6"))
g = int(input("Enter salary 7"))
salaries=np.array([a,b,c,d,e,f,g])
print("All salaries:",salaries)
print("Salaries above 50000:", salaries[salaries>50000])
print("Number of employees:",salaries[salaries>50000].size)

All salaries: [35000 60000 48000 75000 52000 42000 80000]
Salaries above 50000: [60000 75000 52000 80000]
Number of employees: 4


In [5]:
a = int(input("Enter temp 1"))
b = int(input("Enter temp 2"))
c = int(input("Enter temp 3"))
d = int(input("Enter temp 4"))
e = int(input("Enter temp 5"))
f = int(input("Enter temp 6"))
g = int(input("Enter temp 7"))
temperatures=np.array([a,b,c,d,e,f,g],dtype=object)
print("Original",temperatures)
temperatures[temperatures > 40] = "High"
print("After processing:",temperatures)

Original [32 38 41 35 45 39 42]
After processing: [32 38 'High' 35 'High' 39 'High']


In [7]:
sales = np.array([[100, 120, 150, 130],[200, 180, 220, 250],[150, 160, 140, 170]])
print("Sales Matrix:",sales)
print("Product-wise Total:",np.sum(sales,axis=1))
print("Month-wise Total:",np.sum(sales,axis=0))


Sales Matrix: [[100 120 150 130]
 [200 180 220 250]
 [150 160 140 170]]
Product-wise Total: [500 850 620]
Month-wise Total: [450 460 510 550]


In [8]:
a = int(input("Enter salary 1"))
b = int(input("Enter salary 2"))
c = int(input("Enter salary 3"))
d = int(input("Enter salary 4"))
e = int(input("Enter salary 5"))
f = int(input("Enter salary 6"))
salaries=np.array([a,b,c,d,e,f])
uniquesalaries = np.unique(salaries)
sortedsalaries = np.sort(uniquesalaries)
highest = sortedsalaries[-1]
secondhighest = sortedsalaries[-2]
print("Highest Salary:", highest)
print("Second Highest Salary:", secondhighest)


Highest Salary: 90000
Second Highest Salary: 75000


In [4]:
quantity = np.array([[2, 3],[4, 5]])
price = np.array([[100, 200],[150, 250]])
print("Quantity Matrix:",quantity)
print("Price Matrix:",price)
print("Quantity Transpose:",quantity.T)
print("Matrix Multiplication:",quantity@price)

Quantity Matrix: [[2 3]
 [4 5]]
Price Matrix: [[100 200]
 [150 250]]
Quantity Transpose: [[2 4]
 [3 5]]
Matrix Multiplication: [[ 650 1150]
 [1150 2050]]


In [7]:
marks = np.array([40, 50, 60, 70, 80, 90, 100])
print("Original Marks:",marks)
normalized = (marks - np.min(marks)) / (np.max(marks)-np.min(marks))
print("Normalized Marks:",np.round(normalized,4))

Original Marks: [ 40  50  60  70  80  90 100]
Normalized Marks: [0.     0.1667 0.3333 0.5    0.6667 0.8333 1.    ]


In [15]:
sales = np.array([[10, 12, 15, 11, 18],[20, 18, 25, 22, 30],[15, 17, 14, 20, 19],[8, 10, 12, 9, 15]])
products = ["Laptop", "Mobile", "Tablet", "Monitor"]
days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
print("Product-wise Sales:",np.sum(sales, axis=1))
print("Day-wise Sales:",np.sum(sales, axis=0))
bestproduct = np.argmax(np.sum(sales, axis=1))
print("Best Selling Product:", products[bestproduct])
print("Total Sales:", np.sum(sales, axis=1)[bestproduct])
bestday = np.argmax(np.sum(sales, axis=0))
print("Best Sales Day:", days[bestday])
print("Total Sales:", np.sum(sales, axis=0)[bestday])
print("Highest Single-Day Sale:", np.max(sales))
print("Sales above 20:", sales[sales > 20])
print("Overall Average Sales:", np.mean(sales))
producttotal = np.sum(sales, axis=1)
print("Products:")
print(np.array(products)[producttotal > 80])

Product-wise Sales: [ 66 115  85  54]
Day-wise Sales: [53 57 66 62 82]
Best Selling Product: Mobile
Total Sales: 115
Best Sales Day: Friday
Total Sales: 82
Highest Single-Day Sale: 30
Sales above 20: [25 22 30]
Overall Average Sales: 16.0
Products:
['Mobile' 'Tablet']
